spring.application.name=analyzer

spring.datasource.url=jdbc:postgresql://localhost:5432/telemetry_analyzer
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

analyzer.kafka.bootstrap-servers=localhost:9092
analyzer.kafka.snapshot-consumer-group-id=analyzer-snapshot-service
analyzer.kafka.hub-event-consumer-group-id=analyzer-hub-event-service
analyzer.kafka.topics.snapshots=telemetry.snapshots.v1
analyzer.kafka.topics.hubs=telemetry.hubs.v1

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext
